name: ${plugin.name}
main: net.tttproject.ariesbuildings.AriesBuildings
author: Noci
api-version: 1.16
version: ${plugin.version}

depend:
  - ProtocolLib
  - Projekt-System

softdepend:
  - FastAsyncWorldEdit
  - LuckPerms